main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
     path('', views.home, name='home'),
     path('about/', views.about, name='about'),
     path('accounts/', include('django.contrib.auth.urls')),
     path('profile/', views.profile, name='profile'),
     path('profile/edit/', views.profile_edit, name='profile_edit'),
     path('post/<int:post_id>/show/', views.post_show, name='post_show'),
     path('post/<int:post_id>/edit/', views.post_edit, name='post_edit'),
     path('post/<int:post_id>/<int:city_id>/delete/', views.post_delete, name='post_delete'),
     path('post/<int:city_id>/create/', views.post_create, name='post_create'),
     path('profile/<int:profile_id>/add_photo/', views.add_photo, name='add_photo'),
     path('profile/<int:photo_id>/delete/', views.photo_delete, name='photo_delete'),
     path('cities/<int:city_id>/', views.city_show, name='city_show'),
]

wayfarer_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('account/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    current_city = models.CharField(max_length=100, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    image = models.CharField(max_length=1000)

    def __str__(self):
        return f"{self.name}"


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=1500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return f"{self.title}"


class Photo(models.Model):
    url = models.CharField(max_length=200)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"User Profile photo: {self.profile_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Profile, User, Post

from django.contrib.auth.forms import UserCreationForm, forms

class Profile_Form(ModelForm):
    class Meta:
        model = Profile
        fields = ['current_city']

class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

class Post_Form(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']


        

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required

from .models import Profile, User, Post, City, Photo
from .forms import Profile_Form, NewUserForm, Post_Form

from django.conf import settings
from django.core.mail import send_mail

# AWS IMPORTS
import boto3
import uuid
# AWS "Constants"
S3_BASE_URL = 'https://s3-us-west-2.amazonaws.com/'
BUCKET = 'wayfarer-app1'


@login_required
def city_show(request, city_id):
    city_id = City.objects.get(id=city_id)
    city_all = City.objects.all()
    posts = Post.objects.filter(city_id=city_id)
    user = User.objects.get(id=request.user.id)
    photos = Photo.objects.all()
    context = {'posts': posts, 'city_id': city_id, 'city_all': city_all, 'user': user, 'photos': photos}
    return render(request, 'cities/city.html', context)


def home(request):
    error_message = ''
    if request.method == 'POST':
        signup_form = NewUserForm(request.POST)
        username_form = request.POST['username']
        email_form = request.POST['email']
        city = request.POST['current_city']
        if User.objects.filter(username=username_form).exists():
            context = {'error': 'Username is already taken'}
            return render(request, 'home.html', context)
        else:
            if User.objects.filter(email=email_form).exists():
                context = {'error': 'That email is already taken'}
                return render(request, 'home.html', context)
            else:
                if signup_form.is_valid():
                    user = signup_form.save()
                    user.profile.current_city = city
                    user.save()
                    login(request, user)
                    subject = 'Welcome to Wayfarer'
                    message = 'Thank you for registering'
                    email_from = settings.EMAIL_HOST_USER
                    recipient_list = [user.email, ]
                    send_mail(subject, message, email_from, recipient_list)
                    return redirect('profile/')
                else:
                    context = {'error': 'Invalid signup, please try again!'}
                    return render(request, 'home.html', context)

    profile_form = Profile_Form()
    signup_form = NewUserForm()
    login_form = AuthenticationForm()
    context = {'signup_form': signup_form, 'login_form': login_form, 'profile_form': profile_form}
    return render(request, 'home.html', context)


def about(request):
    return render(request, 'about.html')


@login_required
def profile(request):
    if request.method == 'POST':
        profile_form = Profile_Form(request.POST)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('profile')

    user = User.objects.get(id=request.user.id)
    if Profile.objects.filter(user_id=request.user.id):
        profile = Profile.objects.get(user_id=request.user.id)
    else:
        profile = ""
    profile_form = Profile_Form()
    posts = Post.objects.filter(user=request.user)
    context = {'profile': profile, 'profile_form': profile_form, 'user': user, 'posts': posts}
    return render(request, 'profile.html', context)


@login_required
def profile_edit(request):
    profile = Profile.objects.get(user_id=request.user.id)
    user = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        city = request.POST['current_city']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        user.last_name = last_name
        user.first_name = first_name
        user.profile.current_city = city
        user.save()
        return redirect('profile')

    profile_form = Profile_Form(instance=profile)
    user_form = NewUserForm(instance=user)
    context = {'profile_form': profile_form, 'user_form': user_form, 'user': user, 'profile': profile}
    return render(request, 'profiles/edit.html', context)


@login_required
def post_create(request, city_id):
    if request.method == 'POST':
        post_form = Post_Form(request.POST)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.user = request.user
            new_post.city_id = city_id
            new_post.save()
            return redirect('city_show', city_id=city_id)

    post_form = Post_Form()
    context = {'post_form': post_form, 'city_id': city_id}
    return render(request, 'posts/create.html', context)


@login_required
def post_show(request, post_id):
    post = Post.objects.get(id=post_id)
    user = User.objects.get(id=post.user_id)
    auth_user = User.objects.get(id=request.user.id)
    nextvalue = request.GET.get('next')
    photos = Photo.objects.all()
    context = {'post': post, 'user': user, 'auth_user': auth_user, 'next': nextvalue, 'photos': photos}
    return render(request, 'posts/show.html', context)


@login_required
def post_edit(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.user == post.user:
        if request.method == 'POST':
            post_form = Post_Form(request.POST, instance=post)
            if post_form.is_valid():
                post_form.save()
                return redirect('post_show', post_id=post.id)

    post_form = Post_Form(instance=post)
    context = {'post_form': post_form, 'post': post}
    return render(request, 'posts/edit.html', context)


@login_required
def post_delete(request, post_id, city_id):
    item = Post.objects.get(id=post_id)
    nextvalue = request.GET.get('next')
    if request.user == item.user:
        Post.objects.get(id=post_id).delete()
        if nextvalue != 'None':
            return redirect(nextvalue)
        else:
            return redirect('profile')
    else:
        return redirect('city_show', city_id=city_id)

# AWS ADD PHOTO


@login_required
def add_photo(request, profile_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"

            photo = Photo(url=url, profile_id=profile_id, user_id=request.user.id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('profile')


@login_required
def photo_delete(request, photo_id):
    Photo.objects.get(id=photo_id).delete()
    return redirect('profile')

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<div id="container-box" class="ui eight column centered grid">
  <div class="ui link cards">
    <div class="card column">
      <div class="image">
        <img src="/static/resources/BrentNistal.jpeg" />
      </div>
      <div class="content">
        <div class="header">Brent Nistal</div>
        <div class="meta">
          <a>Co-Creator</a>
        </div>
        <div class="description">Software Engineering Immersive</div>
      </div>
      <div class="extra content">
        <span class="right floated"> 2020-2021 </span>
        <span>
          <i class="location arrow icon"></i>
          Spokane, WA
        </span>
      </div>
    </div>
    {% comment %} Card 2 {% endcomment %}
    <div class="card column">
      <div class="image">
        <img src="/static/resources/ClaytonWatkins1.jpeg" />
      </div>
      <div class="content">
        <div class="header">Clayton Watkins</div>
        <div class="meta">
          <a>Co-Creator</a>
        </div>
        <div class="description">Software Engineering Immersive</div>
      </div>
      <div class="extra content">
        <span class="right floated"> 2020-2021 </span>

        <span>
          <i class="location arrow icon"></i>
          Redmond, WA
        </span>
      </div>
    </div>
    {% comment %} CARD 3 {% endcomment %}

    <div class="card column">
      <div class="image">
        <img src="/static/resources/QuincyPham.jpeg" />
      </div>
      <div class="content">
        <div class="header">Quincy Pham</div>
        <div class="meta">
          <a>Co-Creator</a>
        </div>
        <div class="description">Software Engineering Immersive</div>
      </div>
      <div class="extra content">
        <span class="right floated"> 2020-2021 </span>

        <span>
          <i class="location arrow icon"></i>
          Seattle, WA
        </span>
      </div>
    </div>
    {% comment %} Card 4 {% endcomment %}
    <div class="card column">
      <div class="image">
        <img src="/static/resources/GeorgeHu.jpeg" />
      </div>
      <div class="content">
        <div class="header">George Hu</div>
        <div class="meta">
          <a>Co-Creator</a>
        </div>
        <div class="description">Software Engineering Immersive</div>
      </div>
      <div class="extra content">
        <span class="right floated"> 2020-2021 </span>

        <span>
          <i class="location arrow icon"></i>
          Fort Collins, CO
        </span>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Wayfarer</title>
    {% comment %} Font Awesome W Icon
    https://fontawesome.com/icons/weebly?style=brands {% endcomment %}
    <script
      src="https://kit.fontawesome.com/6f4b5c5a8a.js"
      crossorigin="anonymous"
    ></script>

    {% comment %} Semantic UI CSS {% endcomment %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
      integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ=="
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/menu.min.css"
      integrity="sha512-ox96Q1iqhM5TvdY4gVbz6FXoDwsR/Q8jq15kWReQNefC+uUGCv+pkMbLOtr176K3+bfrQQv6gTDAvhL1PUw2YQ=="
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/modal.min.css"
      integrity="sha512-CPLGe+O/BzgzHJKpdBXUuewmlxhlEfQ00zuYg1vcGCjOo88mqMeO1qa8q397ifxm18D12Go8OF7A42CjOKEl/g=="
      crossorigin="anonymous"
    />

    {% comment %} SWIPER CDN {% endcomment %}
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css" />
    <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />

    <style type="text/css">
      .hidden.menu {
        display: none;
      }

      .masthead.segment {
        min-height: 700px;
        padding: 1em 0em;
      }
      .masthead .logo.item img {
        margin-right: 1em;
      }
      .masthead .ui.menu .ui.button {
        margin-left: 0.5em;
      }
      .masthead h1.ui.header {
        margin-top: 3em;
        margin-bottom: 0em;
        font-size: 4em;
        font-weight: normal;
      }
      .masthead h2 {
        font-size: 1.7em;
        font-weight: normal;
      }

      .ui.vertical.stripe {
        padding: 8em 0em;
      }
      .ui.vertical.stripe h3 {
        font-size: 2em;
      }
      .ui.vertical.stripe .button + h3,
      .ui.vertical.stripe p + h3 {
        margin-top: 3em;
      }
      .ui.vertical.stripe .floated.image {
        clear: both;
      }
      .ui.vertical.stripe p {
        font-size: 1.33em;
      }
      .ui.vertical.stripe .horizontal.divider {
        margin: 3em 0em;
      }

      .quote.stripe.segment {
        padding: 0em;
      }
      .quote.stripe.segment .grid .column {
        padding-top: 5em;
        padding-bottom: 5em;
      }

      .footer.segment {
        padding: 5em 0em;
      }

      .secondary.pointing.menu .toc.item {
        display: none;
      }

      @media only screen and (max-width: 700px) {
        .ui.fixed.menu {
          display: none !important;
        }
        .secondary.pointing.menu .item,
        .secondary.pointing.menu .menu {
          display: none;
        }
        .secondary.pointing.menu .toc.item {
          display: block;
        }
        .masthead.segment {
          min-height: 350px;
        }
        .masthead h1.ui.header {
          font-size: 2em;
          margin-top: 1.5em;
        }
        .masthead h2 {
          margin-top: 0.5em;
          font-size: 1.5em;
        }
      }
    </style>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />

    {% comment %} jQuery js {% endcomment %}
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"
    ></script>
    {% comment %} Semantic UI js {% endcomment %}
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"
      integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw=="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/modal.min.js"
      integrity="sha512-aAW/TaSuYfyjTcMsaYP67Dwe0vI5d7ej9X7NJBPkhafB+D5kx57flRNo8+tOXWA0Gcq0MBmhPatrvn1YwvH9gQ=="
      crossorigin="anonymous"
    ></script>

    {% comment %} Sidebar js {% endcomment %}
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/sidebar.min.js"
      integrity="sha512-1tmZBYaLOUohS48wc5egam1rTAIi71yvIpxj0FXHo6FskhgMF3LyCAdLvCFYi4e/L0GfH6BFtDBFD2wVa645Dg=="
      crossorigin="anonymous"
    ></script>
    {% comment %} Visibility js {% endcomment %}
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/visibility.min.js"
      integrity="sha512-pcX/bEmbHWxW0fvRU70A6UqVXm0Z1tBJTwSLHE3hE8AAhG4hDL8R19Oho4DmdCNNYrgDSyHhH+ALNg5d5SFxxw=="
      crossorigin="anonymous"
    ></script>
    {% comment %} SWIPER {% endcomment %}
    <script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

    <script>
      $(document).ready(function () {
        // fix menu when passed
        /* REVIEW: FIXED MENU HERE, WITH HAMBURGER MENU?*/
        $(".masthead").visibility({
          once: false,
          onBottomPassed: function () {
            $(".fixed.menu").transition("fade in");
          },
          onBottomPassedReverse: function () {
            $(".fixed.menu").transition("fade out");
          },
        });
        

        // create sidebar and attach to menu open
        $(".ui.sidebar").sidebar("attach events", ".toc.item");

        $("#login_modal").click(function () {
          $(".ui.modal.login").modal("show");
        });

        $("#hide_modal").click(function () {
          $(".ui.modal.login").modal("hide");
        });

        $("#signup_modal").click(function () {
          $(".ui.modal.signup").modal("show");
        });

        $(".delete_modal").click(function () {        
          $("#modal-"+this.id).modal("show");       
        });
 
        $("#post_modal").click(function () {
          $(".ui.modal.post").modal("show");
        });
      });
    </script>
  </head>

  <body
    id="body"
    class="pushable"
    data-new-gr-c-s-check-loaded="14.991.0"
    data-gr-ext-installed=""
    cz-shortcut-listen="true"
  >
    {% comment %} ==== MODAL CONTENT ==== {% endcomment %}
<div class="ui modal login"> <i class="close icon"></i>
    <div class="header">Login</div>
    <div class="content">
      <form method="POST" action = "{% url 'login' %}">
          {% csrf_token %}
{% comment %} NEW SEMANTIC FORM {% endcomment %}
            <div class="ui equal width form error">
              <div class="fields">
                <div class="field">
                  <label>Username</label>
                  <input type="text" placeholder="Username" name="username">
                </div>
                <div class="field">
                  <label>Password</label>
                  <input type="password" name="password">
                </div>
              </div>
            </div>
            {% if error_message %}
              <div class="ui error message">
                <div class="header">Action Forbidden</div>
                 <p>{{error_message}}</p>
              </div>
            {% endif %}
    <div class="actions">
          <input type="submit" class="ui inverted button" value="Login"/>
          <input type="hidden" name="next" value="{{ next }}"/>
    </div>
      </form>    
    </div>
</div>

<div class="ui modal signup"> <i class="close icon"></i>
    <div class="header">Sign Up</div>
    <div class="content">
    {% comment %} NEW FORM {% endcomment %}
      <form method="POST" action = "{% url 'home' %}">
          {% csrf_token %}
          {% comment %} NEW SEMANTIC FORM {% endcomment %}
            <div class="ui equal width form">
              
                <div class="field">
                  <label>Username</label>
                  <input type="text" placeholder="Username" name="username" required>
                </div>
                <div class="fields">
                <div class="field">
                  <label>First Name</label>
                  <input type="text" name="first_name" placeholder="John" required>
                </div>
                <div class="field">
                  <label>Last Name</label>
                  <input type="text" name="last_name" placeholder="Smith" required>
                </div>
                </div>
                    <div class="field">
                  <label>Email</label>
                  <input type="email" name="email" placeholder="TravelPro@Wayfarer.com" required>
                </div>
                <div class="field">
                  <label>Current City</label>
                  <input type="text" name="current_city" placeholder="Seattle" required>
                </div>
                <div class="ui message">
                  <div class="header">Password requirements</div>
                  <ul class="list">
                    <li>Minimum 8 characters.</li>
                    <li>Can't be a commonly used password</li>
                    <li>Can't be entirely numeric.</li>
                    <li>Can't be too similar to personal information</li>
                  </ul>
                </div>
                <div class="fields">
                    <div class="field">
                  <label>Password</label>
                  <input type="password" name="password1" placeholder="Password" required>
                </div>    <div class="field">
                  <label>Password Confirmation</label>
                  <input type="password" name="password2" placeholder="Password" required>
                </div>
                </div>
            </div>
            {% if error %}
              <div class="ui error message">
                <div class="header">Action Forbidden</div>
                 <p>{{error}}</p>
              </div>
            {% endif %}
              <div class="actions">
          <input type="submit" class="ui inverted button" value="Sign Up"/>
          {% comment %} REVIEW: Cancel button to close modal/redirect to SAME page {% endcomment %}
          {% comment %} <div class="ui button" id="hide_modal">Cancel</div> {% endcomment %}
          <input type="hidden" name="next" value="{{ next }}"/>
      
    </div>
      </form>   

{% comment %} ORIGINAL FORM {% endcomment %}
      {% comment %} <form method="POST" action = "{% url 'home' %}">
          {% csrf_token %}
          {{ signup_form.as_p }}
          <input type="submit" class="ui inverted button" value="Sign Up"/>
          
          <div class="ui button" id="hide_modal">Cancel</div>
          <input type="hidden" name="next" value="{{ next }}"/>
      </form>    {% endcomment %}

    </div>
</div>











{% comment %} ==== NAV CONTENT ==== {% endcomment %}


    <!-- Sidebar NAV Menu -->
    <div class="ui vertical inverted sidebar menu left">
      <a href="/" class="active item">Home</a>
      <a href="/about" class="item">About</a>
      {% if user.is_authenticated %}
      <a href="/profile" class="item">Profile</a>
      <a class="item" href="{% url 'logout' %}">Log Out</a>
      {% endif %}
    </div>

    <!-- MAIN NAV MENU Contents -->
    <div class="pusher">
      <div id="masthead" class="ui inverted vertical masthead center aligned segment">
        <div id="navbar" class="ui container">
          <div class="ui large secondary inverted pointing menu">
            <a class="toc item">
              <i class="sidebar icon"></i>
            </a>
            <a href="/" class="fab fa-weebly" id="logo-nav"></a>

            <a href="/" class="item">Home</a>
            <a href="/about" class="item">About</a>
            {% if user.is_authenticated %}
            <a href="/profile" class="item">Profile</a>
            <a href="/cities/1" class="item">City</a>
            {% endif %}
            <div class="right item">
              {% if user.is_authenticated %}
              <a class="ui inverted button" href="{% url 'logout' %}"
                >Log Out</a
              >
              {% else %}
              <a class="ui inverted button" id="login_modal">Login</a>
              <a class="ui inverted button" id="signup_modal">Sign Up</a>
              {% endif %}
            </div>
          </div>
      </div>

      {% comment %} ===== BLOCK CONTENT ===== {% endcomment %} 
      {% block content%} {% endblock %} 
      
      {% comment %} ==== FOOTER ==== {% endcomment %}
      <div id="footer" class="ui inverted vertical footer segment">
        <div class="ui container">
          <div
            class="ui stackable inverted divided equal height stackable grid"
          >
            <div class="three wide column">
              <h4 class="ui inverted header">Connect</h4>
              <div class="ui inverted link list">
                <a href="/about" class="item">About</a>
                
              </div>
            </div>
            <div class="three wide column">
              <h4 class="ui inverted header">Navigate</h4>
              <div class="ui inverted link list">
              {% if user.is_authenticated %}
            <a href="/profile" class="item">Profile</a>
            <a href="/cities/1" class="item">City</a>
            <a class="item" href="{% url 'logout' %}"
                >Log Out</a
              >
               {% else %}
              <a href="/" class="item">Home</a>
        
            {% endif %}
              </div>
            </div>
            <div class="seven wide column">
              <h4 class="ui inverted header">Wayfarer</h4>
              <p>
                Wayfarer app &copy 2021
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

main_app/templates/profile.html
{% extends 'base.html' %} {% block content %}

<div id="container-box" class="ui center aligned stackable grid container">
  <div id="left-box" class="four wide computer three wide tablet six wide mobile column">


    <h3 class="ui center aligned header">{{ user.first_name}} {{user.last_name}}</h3>

    <div class="ui segment">
      {% comment %} PHOTO {% endcomment %}
      {% for photo in profile.photo_set.all %}
      <img class="profile-img" src="{{photo.url}}">
      <a href="{% url 'photo_delete' photo_id=photo.id %}">Delete</a>
      {% empty %}
      <img class="profile-img" src="https://assets.stickpng.com/images/585e4bf3cb11b227491c339a.png">
      {% comment %} <div class="">No Photos Uploaded</div> {% endcomment %}


      {% comment %} PHOTO FORM {% endcomment %}
      <form action="{% url 'add_photo' profile.id %}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}

        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" class="btn" value="Upload Photo">
      </form>
      {% endfor %}


      {% comment %} User info {% endcomment %}
      <p>Date Joined: {{ user.date_joined }}</p>
      <p> Email: {{ user.email }}</p>
      <p>Current City: {{ profile.current_city }}</p>
      {% if profile != "" %}
      <a href="{% url 'profile_edit' %}" class="ui inverted button">Edit Profile</a>
      {% endif %}
    </div>

    {% if profile == "" %}
    <form action="{% url 'profile' %}" method="POST">
      {% csrf_token %}
      {{profile_form.as_p}}
      <input class='ui inverted button' type="submit" value='Add Current City'>
    </form>
    {% endif %}
  </div>

  <div id="right-box" class="nine wide computer nine wide tablet six wide mobile column">
    <h3 class="ui center aligned header">Posts</h3>
    {% for post in posts %}
    <div class="ui segment">
      <a href="{% url 'post_show' post_id=post.id %}">
        <p>{{ post.title }}</p>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

</div>

{% endblock %}